---
- name: Configure all DevSecOps servers
  hosts: all
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install common packages
      apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - vim
          - net-tools
        state: present
